
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int READ = 11;
  public static final int LP = 16;
  public static final int WHILE = 14;
  public static final int RP = 17;
  public static final int END = 8;
  public static final int TRUE = 2;
  public static final int WRITE = 10;
  public static final int ID = 4;
  public static final int SUB = 12;
  public static final int BEGIN = 7;
  public static final int DO = 15;
  public static final int STRINGLITERAL = 6;
  public static final int EOF = 0;
  public static final int INTLITERAL = 5;
  public static final int FALSE = 3;
  public static final int error = 1;
  public static final int SEM = 13;
  public static final int EQ = 9;
  public static final int MUL = 18;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "TRUE",
  "FALSE",
  "ID",
  "INTLITERAL",
  "STRINGLITERAL",
  "BEGIN",
  "END",
  "EQ",
  "WRITE",
  "READ",
  "SUB",
  "SEM",
  "WHILE",
  "DO",
  "LP",
  "RP",
  "MUL"
  };
}

